### ISSUE TITLE
Running steamctl on Windows errors due to SIGPIPE not existing

### ISSUE THREAD

**Issue by DMzda** [ValvePython/steamctl#3]
Using python 3.7.3 64bit on Windows 10.

The full error:
```
> steamctl
Traceback (most recent call last):
  File "c:\users\mazin\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mazin\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mazin\AppData\Local\Programs\Python\Python37\Scripts\steamctl.exe\__main__.py", line 5, in <module>
  File "c:\users\mazin\appdata\local\programs\python\python37\lib\site-packages\steamctl\__main__.py", line 4, in <module>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name 'SIGPIPE' from 'signal' (c:\users\mazin\appdata\local\programs\python\python37\lib\signal.py)
```

From the [docs](https://docs.python.org/3/library/signal.html#signal.signal):

> On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, SIGTERM, or SIGBREAK. A ValueError will be raised in any other case.

so I assume those are the only signals that exist on Windows.

**Comment by rossengeorgiev** [comment]
Thanks!
