### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by murlakatamenka** [ValvePython/steamctl#5]
Trying to get list of depots for a given appid fails:

```sh
 steamctl -l debug --user <username> depot info -a 220

[DEBUG] steamctl: Parsed args: {'log_level': 'debug', 'anonymous': False, 'user': '<username>', 'command': 'depot', '_cmd_func': 'steamctl.commands.depot.gcmds:cmd_depot_info', 'subcommand': 'info', 'cell_id': None, 'os': 'any', 'file': None, 'app': 220, 'depot': None, 'manifest': None}
[DEBUG] CachingCDNClient: Trying to fetch content servers from Steam API
[DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): api.steampowered.com:443
[DEBUG] urllib3.connectionpool: https://api.steampowered.com:443 "GET /IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=0&max_servers=20&format=json HTTP/1.1" 200 712
[DEBUG] CachingCDNClient: No steam licenses found on SteamClient instance
[INFO] CMClient: Attempting login as: <username>
Username: <username>
Password: 
[DEBUG] CMClient: Attempting login
[DEBUG] CMClient: Connect initiated.
[DEBUG] CMServerList: Attempting bootstrap via WebAPI
[DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): api.steampowered.com:443
[DEBUG] urllib3.connectionpool: https://api.steampowered.com:443 "GET /ISteamDirectory/GetCMList/v1/?cellid=0&format=json HTTP/1.1" 200 805
[DEBUG] CMServerList: Recieved 100 servers from WebAPI
[DEBUG] CMServerList: Added 100 new CM addresses.
[DEBUG] Connection: Attempting connection to ('162.254.193.6', 27019)
[DEBUG] Connection: Connected.
[DEBUG] CMClient: Emit event: 'connected'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/murla/.local/lib/python3.7/site-packages/steam/client/__init__.py", line 99, in _parse_message
    result = CMClient._parse_message(self, message)
  File "/home/murla/.local/lib/python3.7/site-packages/steam/core/cm.py", line 276, in _parse_message
    if self.count_listeners(emsg) or self.verbose_debug:
AttributeError: 'CachingSteamClient' object has no attribute 'count_listeners'
2019-09-03T20:43:02Z <Greenlet at 0x7fd6ecc254d0: <bound method SteamClient._parse_message of <CachingSteamClient(('162.254.193.6', 27019)) online>>(b'\x17\x05\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff)> failed with AttributeError
```

`steamctl` was installed with

```sh
pip install --user steamctl
```
Running Arch Linux, Python 3.7.4 here.

**Comment by rossengeorgiev** [comment]
Can you provide the output of `pip --user freeze` ?

**Comment by murlakatamenka** [comment]
There it is

```
argcomplete==1.10.0
bencoder.pyx==2.0.0
cachetools==3.1.1
certifi==2019.6.16
checkio-client==0.1.16
docopt==0.6.2
dottorrent==1.10.1
dottorrent-cli==1.10.2
epr==2.2.8
gevent==1.4.0
gevent-eventemitter==2.0
humanfriendly==2.4
imageio==2.5.0
monotonic==1.5
networkx==2.3
pipx==0.14.0.0
protobuf==3.7.1
protobuf3-to-dict==0.1.5
pycryptodomex==3.8.2
pygame==1.9.5
python-valve==0.2.1
PyWavelets==1.0.3
requests==2.21.0
scikit-image==0.15.0
scipy==1.2.1
steam==1.0.0a4
steamapi==0.1
steamctl==0.3.3
steamfiles==0.1.3
tqdm==4.33.0
ueberzug==18.1.4
urllib3==1.24.3
userpath==1.2.0
vdf==3.2
```

**Comment by rossengeorgiev** [comment]
`gevent-eventemitter` needs to be `>=2.1`

**Comment by murlakatamenka** [comment]
Upgrading `gevent-eventemitter` (2.0 -> 2.1) solved the issue.
```sh
pip install --user --upgrade gevent-eventemitter
```
Thanks!

**Comment by rossengeorgiev** [comment]
Push an update to `steam` package to resolve the issue. https://github.com/ValvePython/steam/commit/c708ed0c75f226c3cdf95178fd7a9011665a6a85
