### ISSUE TITLE
depot commands fail when the app needs an access token

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/steamctl#7]
```python
# steamctl depot info -a 1042420
[INFO] Attempting anonymous login
[INFO] Login to Steam successful
[INFO] Checking licenses
[INFO] Checking change list
[INFO] Getting manifests for 'public' branch
Traceback (most recent call last):
  File "/dev/steam-python/e3/bin/steamctl", line 11, in <module>
    load_entry_point('steamctl', 'console_scripts', 'steamctl')()
  File "/dev/steamctl-python/steamctl/__main__.py", line 50, in main
    rcode = cmd_func(args=args)
  File "/dev/steamctl-python/steamctl/commands/depot/gcmds.py", line 113, in cmd_depot_info
    with init_clients(args) as (s, cdn, manifests):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/dev/steamctl-python/steamctl/commands/depot/gcmds.py", line 91, in init_clients
    for manifest in cdn.get_manifests(args.app, filter_func=branch_filter, decrypt=False):
  File "/dev/steamctl-python/steam/client/cdn.py", line 676, in get_manifests
    depots = self.get_app_depot_info(app_id)
  File "/dev/steamctl-python/steamctl/clients.py", line 181, in get_app_depot_info
    self.app_depots[app_id] = appinfo['depots']
KeyError: 'depots'
```

Some context: https://github.com/ValvePython/steam/issues/216

**Comment by rossengeorgiev** [comment]
fixed in c3c484f4bcfba6b74b6d9e61bbf9328da657b21b
