### ISSUE TITLE
[BUG] steamctl not saving depot_keys

### ISSUE THREAD

**Issue by nutterthanos** [ValvePython/steamctl#82]
**Description**

running any command that would normally trigger the function that saves depot_key's to depot_keys.json is not happening and even with depot_keys stored its not reading any existing depot_keys.json either

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

run any command that would save depot_keys to depot_keys.json

**Expected behavior**

it is meant to save depot_keys and read from it too

**What actually happend**
Description of what actually happend

it was not saving anything and as such i can't use depot download with local manifest files since it fails with no depot_key or whatever.

**Logs**
<details><summary>steamctl -l debug</summary>
(Include logs related ot the issue. Use `steamctl -l debug` to get detailed log)
```
[DEBUG] steamctl: Parsed args: {'versions_report': None, 'log_level': 'debug', 'anonymous': False, 'user': None, 'password': None, 'command': 'depot', '_cmd_func': 'steamctl.commands.depot.gcmds:cmd_depot_download', 'subcommand': 'download', 'cell_id': None, 'os': 'any', 'output': '', 'no_directories': False, 'no_progress': False, 'file': [[<_io.BufferedReader name='C:\\Users\\conno\\AppData\\Local\\steamctl\\steamctl\\Cache\\manifests\\284160_284161_2529170545716926949'>]], 'app': 284160, 'depot': 284161, 'manifest': 2529170545716926949, 'branch': 'public', 'skip_depot': None, 'skip_login': False, 'skip_licenses': False, 'vpk': False, 'skip_verify': False, 'name': None, 'regex': None}
[DEBUG] steamctl.utils.storage: Opening file (r): C:\Users\conno\AppData\Local\steamctl\steamctl\cs_servers.json
[DEBUG] CachingCDNClient: No steam licenses found on SteamClient instance
[INFO] steamctl.commands.depot.gcmds: Locating and counting files...
[INFO] steamctl.commands.depot.gcmds: Processing manifest (2529170545716926949) '284160_284161_2529170545716926949' ...
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\html\images\icons
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): lancache.steamcontent.com:80
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (2): lancache.steamcontent.com:80
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (3): lancache.steamcontent.com:80
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\core\scripts\gui
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (4): lancache.steamcontent.com:80
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\tools\gui\images\GUI-editor
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (5): lancache.steamcontent.com:80
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\tools\classIcons
[DEBUG] urllib3.connectionpool: Starting new HTTP connection (6): lancache.steamcontent.com:80
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/36e8e7ee50a9138fad1dd0e56aefa42b886d4f7b HTTP/1.1" 200 1120
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/6197eb13b4254f77f16833e1a9a8640e939d574c HTTP/1.1" 200 336
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/d12a75c8056bc6b4fb89560d57ea78e9419d7c8d HTTP/1.1" 200 1184
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/37092211523603d0cb76f04b6c1a4e155bae7af3 HTTP/1.1" 200 320
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/d3e06d33f4f46fc4a447d6a524b70a203b25b5a2 HTTP/1.1" 200 448
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
[DEBUG] urllib3.connectionpool: http://lancache.steamcontent.com:80 "GET /depot/284161/chunk/4aaa0e7517d34d25e9b06b266c963c3bbbef73fb HTTP/1.1" 200 512
[DEBUG] SteamClient: Trying to send message when not connected. (discarded)
Data :   0%|                                                                               | 0.00/3.28G [00:10<?, ?B/s]Traceback (most recent call last):                                                | 6/4034 [00:10<1:51:58,  1.67s/ file]
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e42840: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'html\\images\\icons\\chart_pie_delete.png', 983)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e43e20: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'html\\images\\icons\\bullet_arrow_down.png', 201)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e40c20: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'core\\scripts\\gui\\guiMusicPlayer.gui', 5983)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e179c0: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'tools\\classIcons\\GuiTreeViewCtrl.png', 196)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e40fe0: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'html\\images\\icons\\textfield_add.png', 321)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError

[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\core\art\special
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\tools\editorClasses\scripts\guiClasses
[DEBUG] steamctl.utils.storage: Making dirs: C:\Users\conno\steamctl\Bin32\locales
Data :   0%|                                                                               | 0.00/3.28G [00:10<?, ?B/s]Traceback (most recent call last):                                               | 11/4034 [00:10<1:36:37,  1.44s/ file]
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Python312\Lib\site-packages\steamctl\clients.py", line 252, in download_to
    data = self.manifest.cdn_client.get_chunk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 607, in get_chunk
    data = symmetric_decrypt(resp.content, self.get_depot_key(app_id, depot_id))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\steam\client\cdn.py", line 550, in get_depot_key
    raise SteamError("Failed getting depot key",
steam.exceptions.SteamError: (16) Failed getting depot key
2024-02-16T23:48:26Z <Greenlet at 0x1d167e40360: <bound method CTLDepotFile.download_to of <CTLDepotFile(284160, 284161, 2529170545716926949, 'tools\\gui\\images\\GUI-editor\\align-top_h.png', 383)>>('', no_make_dirs=False, pbar=<steamctl.utils.tqdm.tqdm object at 0x000001D166A9, verify=True)> failed with SteamError
```
</details>

**Versions Report**
<details><summary>steamctl --versions-report</summary>
(Run steamctl --versions-report and paste the output below)

```yaml
steamctl: 0.9.5

Dependencies:
               steam: 1.4.4
             appdirs: 1.4.4
         argcomplete: 3.2.2
                tqdm: 4.66.2
               arrow: 1.3.0
            pyqrcode: 1.2.1
      beautifulsoup4: 4.12.3
                 vpk: 1.4.0
                 vdf: 3.4
 gevent-eventemitter: 2.1
              gevent: 24.2.1
            greenlet: 3.0.3
              pyyaml: Not Installed
       pycryptodomex: 3.20.0
            protobuf: 3.20.3

Python runtime:
          executable: C:\Python312\python.exe
             version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
            platform: win32

System info:
              system: Windows
             machine: AMD64
             release: 11
             version: 10.0.22621
```
</details>

**Comment by nutterthanos** [comment]
@woctezuma actually i didn't realize it does not save it until download is done lol
it is reading it too just had a broken file or something else idk
also didn't have the right key in the file before anyways.
